name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what happened vs what you expected.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Open a .mzscene file with '...'
        2. Add a Show Picture event
        3. Click '...'
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App version
      description: Found in Help > About.
      placeholder: v1.3.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.
    validations:
      required: false
