name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or what workflow would it improve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you'd like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about.
    validations:
      required: false
